### ISSUE TITLE
MongoDB+SRV protocol?

### ISSUE THREAD

**Issue by jayands** [South-Paw/koa-mongoose#1]
I'm trying to convert over to using this so as to start the connection *with* the Koa server, etc., however, I noticed that you don't actually seem to support the `mongodb+srv://` protocol, which is what's recommended/forced by [MongoDB Atlas](https://docs.atlas.mongodb.com/driver-connection/). Furthermore, *their* documentation is written such that it seems as though no other form is supported. Do you have any intent on supporting that form, and if not, how does one work around it?

**Comment by South-Paw** [comment]
Hi, it looks like it could be supported by adding a new config key of `protocol` to packages config which would default to `mongodb`. You could then override this to be `mongodb+srv` for your use case.

Do you see any issues with this and are there any other parts of the URL that need to change to support you use case?

**Comment by jayands** [comment]
Looks pretty good to me; the only thing to check for is the fact that the port number is forbidden in the `mongodb+srv` use case, as I'm understanding it.

This is what I was doing in the old script:

```typescript
let SAFE_URL: string; // "safe url" for logging purposes
if (/srv/i.test(MONGO_PROTOCOL)) {
  SAFE_URL = `${MONGO_HOST}`;
} else {
  SAFE_URL = `${MONGO_HOST}:${MONGO_PORT}`;
}
const MONGO_URL = `${MONGO_PROTOCOL}://${MONGO_USER}:${MONGO_PASS}@${SAFE_URL}`;
```

**Comment by South-Paw** [comment]
I know it's been a month - but looking back on this issue I think you can simply solve it by using the existing `url` or `uri` parameters in the config - these bypass the url creation.

**Comment by South-Paw** [comment]
Upon testing this, `muri` would have thrown an error in `1.0.0` but as of `1.1.0` it will not anymore as `muri` has been removed from the package (see: https://github.com/aheckmann/muri/issues/17)

I have also added a note about using `mongodb+srv` in the readme now.
